### ISSUE TITLE
Printing adjustment results causes adjust.exe to crash 

### ISSUE THREAD

**Issue by ibaran73** [icsm-au/DynAdjust#10] opened 2019-01-02 04:56 UTC
When adjusting some jurisdictions networks on our PC during the final printing phase of the adjustment results the 'adjust.exe' crashes. 

By eliminating commands one by one from the adjust line we were able to figure out that the problem is with: --output-adj-gnss-units 1. In fact, it is the argument value ‘1’ that tigers the crash. If we set --output-adj-gnss-units to default 0 [as measured] all is fine and the adjustment results get printed no problem. However, when the argument is set to 1 [east, north, up] the adjust.exe crashes. Perhaps something upsets the conversion from XYZ to ENU during the printing phase.
 
![crash](https://user-images.githubusercontent.com/46308847/50580558-de568a80-0e8a-11e9-8eb6-9f732b180ebf.JPG)

**Comment by rogerfraser** [comment] 2019-08-29 04:09
As discussed, I haven't been able to replicate this problem on any of the data sets that I have.  From our discussions, this sounds like it’s more than just converting GNSS vectors from cartesian to local, and might be related to a combination of options (i.e. report-results). 

I see from the image that this network has 896,258 measurements. It’s extremely difficult trying to debug a network of this size. In order to isolate the cause of the problem, a smaller set of sample files will be needed.  If someone can provide smaller sample files, I'll devote some time to it.

I'd be interested to know if anyone else experienced this problem?

**Comment by rogerfraser** [comment] 2020-05-22 04:48
This issue has now been resolved by pull request https://github.com/icsm-au/DynAdjust/pull/47, merged into the main branch.

**Closed by rogerfraser** 2020-05-22 04:48 UTC
Labels: bug
